_BASE_: "Base-COCO-RCNN-FPN.yaml"

MODEL:
    PROBABILISTIC_MODELING:
        # Settings for monte-carlo dropout
        DROPOUT_RATE: 0.1 # 0.0 for no dropouts

        # One of the following Loss types: 'none' or 'negative_log_likelihood', 'second_moment_matching', 'energy_loss'.
        BBOX_COV_LOSS:
            NAME: 'energy_loss'
            COVARIANCE_TYPE: 'diagonal' # One of the following: 'full', 'diagonal'