_BASE_: "Base-COCO-RCNN-FPN.yaml"

MODEL:
    PROBABILISTIC_MODELING:
        # One of the following Loss types: 'none' or 'negative_log_likelihood', 'second_moment_matching', 'energy_loss'.
        # dmmv2 for ann unc
        BBOX_COV_LOSS:
            NAME: 'dmmv2'
            COVARIANCE_TYPE: 'diagonal' # One of the following: 'full', 'diagonal'
    ROI_HEADS:
        NUM_CLASSES: 20
    WEIGHTS: "./pretrained_weights/faster_rcnn_R_50_FPN_3x_reg_covar_nll.pth"

SOLVER:
    IMS_PER_BATCH: 8
    BASE_LR: 0.001
    STEPS: (50000, 60000)
    MAX_ITER: 70000
    CHECKPOINT_PERIOD: 5000
    WARMUP_ITERS: 500

DATASETS:
    TRAIN: ("vbdcxr_train_unc",)
    TEST: ("vbdcxr_val",)
TEST:
    EVAL_PERIOD: 5000
#DATALOADER:
#    FILTER_EMPTY_ANNOTATIONS: False
#    NUM_WORKERS: 0