_BASE_: "Base-COCO-RetinaNet.yaml"

MODEL:
    PROBABILISTIC_MODELING:
        # One of the following Loss types: 'none' or 'negative_log_likelihood', 'second_moment_matching', 'energy_loss'.
        # dmmv2 for ann unc
        BBOX_COV_LOSS:
            NAME: 'dmmv2'
            COVARIANCE_TYPE: 'diagonal' # One of the following: 'full', 'diagonal'
    ROI_HEADS:
        NUM_CLASSES: 20
    RETINANET:
        NUM_CLASSES: 20
    WEIGHTS: "./pretrained_weights/retinanet_R_50_FPN_3x_reg_var_nll.pth"

SOLVER:
    IMS_PER_BATCH: 16
    BASE_LR: 0.001  # Note that RetinaNet uses a different default learning rate
    STEPS: (30000, 35000)
    MAX_ITER: 40000
    CHECKPOINT_PERIOD: 2000
    WARMUP_ITERS: 500

DATASETS:
    TRAIN: ("vbdcxr_train_unc",)
    TEST: ("vbdcxr_val",)
TEST:
    EVAL_PERIOD: 2000
#DATALOADER:
#    FILTER_EMPTY_ANNOTATIONS: False
#    NUM_WORKERS: 0