_BASE_: "Base-COCO-RetinaNet.yaml"

MODEL:
    PROBABILISTIC_MODELING:
        # One of the following Loss types: 'none' or 'negative_log_likelihood', 'second_moment_matching', 'energy_loss'.
        BBOX_COV_LOSS:
            NAME: 'none'
    ROI_HEADS:
        NUM_CLASSES: 20
    RETINANET:
        NUM_CLASSES: 20
    WEIGHTS: "./pretrained_weights/retinanet_R_50_FPN_3x.pth"

SOLVER:
    IMS_PER_BATCH: 16
    BASE_LR: 0.001  # Note that RetinaNet uses a different default learning rate
    STEPS: (31000, 37000)
    MAX_ITER: 40000
    CHECKPOINT_PERIOD: 2000
    WARMUP_ITERS: 500

DATASETS:
    TRAIN: ("vocmix_train_ind",)
    TEST: ("vocmix_val",)
TEST:
    EVAL_PERIOD: 2000